### PR TITLE
cask-repair: add -m flag for adding messages to PRs

### PR DESCRIPTION
**Pull request by brianmorton**
per https://github.com/vitorgalvao/tiny-scripts/issues/138#issuecomment-403164100

example: https://github.com/Homebrew/homebrew-cask/pull/49366

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Mind testing the updated version before I merge and bump the formula version?

**Comment by commitay** [comment]
`commit_message` is used by `commit_message="Update ${cask_name} to ${cask_version}"`

https://github.com/Homebrew/homebrew-cask/pull/49376
https://github.com/Homebrew/homebrew-cask/pull/49377

```diff
diff --git a/cask-repair b/cask-repair
index 52500ea..87c643e 100755
--- a/cask-repair
+++ b/cask-repair
@@ -368,7 +368,7 @@ while [[ "${1}" ]]; do
       shift
       ;;
     -m | --message)
-      commit_message="${2}"
+      pr_message="${2}"
       shift
       ;;
     -b | --blind-submit)
@@ -568,7 +568,7 @@ for cask in "${@}"; do
   fi

   [[ -n "${issue_to_close}" ]] && hub_message+="\n\nCloses #${issue_to_close}."
-  [[ -n "${commit_message}" ]] && hub_message+="\n\n${commit_message}"
+  [[ -n "${pr_message}" ]] && hub_message+="\n\n${pr_message}"
   pr_link=$(hub pull-request -b "${submit_pr_to}" -h "${submit_pr_from}" -m "$(echo -e "${hub_message}")")

   if [[ -n "${pr_link}" ]]; then
```

**Comment by brianmorton** [comment]
So are we all good now? Did somebody do a test of this?

**Comment by commitay** [comment]
Current version works fine. 👍 https://github.com/Homebrew/homebrew-cask/pull/49383

**Pull request merged**
