### PR TITLE
cask-repair: audit options match CI checks

### PR DESCRIPTION
**Pull request by 404NetworkError**
I noticed that audit checks in `cask-repair` would pass but would fail when run on Travis. When looking at the [Homebrew CI file](https://github.com/Homebrew/homebrew-cask/blob/master/cmd/brewcask-ci.rb#L42-L44), I noticed that Travis will run the command line equivalent to `brew cask audit --download --appcast --token-conflicts [token]`. This script currently runs the basic `brew cask audit [token]`.

It would be nice to have both this script and Travis run the same `brew cask audit` commands.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but [this is the correct fix](https://github.com/vitorgalvao/tiny-scripts/commit/80fbda6f624b5158c20780c70d53a1c56f21fa3f#diff-4a8d6dd423163721b17011afb643d0b7).

**Comment by 404NetworkError** [comment]
That works better. I wasn't sure if `--download` should be included in the main `brew cask audit` check or not.

**Comment by vitorgalvao** [comment]
> I wasn't sure if `--download` should be included in the main `brew cask audit` check or not.

`cask-repair` generates the shasum, so it will be correct. The check would just make the process longer.

**Comment by vitorgalvao** [comment]
Had a thought about it, and I’m going to reverse. `--appcast` should not be run when updating in `cask-versions`, and the token conflict is a guideline, not a rule that prevents submission.

**Comment by 404NetworkError** [comment]
The lower barrier to entry for newcomers, the better in my opinion; so I understand that not making `--appcast` a requirement will help.

It's just convenient to run a single command and you're almost always guaranteed the CI will not fail. (The whole reason I brought it up and suggested the change was that I had the CI fail on the appcast while running this script didn't.)

**Comment by vitorgalvao** [comment]
> It's just convenient to run a single command and you're almost always guaranteed the CI will not fail.

On the other hand, this was [making legitimate submissions fail](https://github.com/vitorgalvao/tiny-scripts/issues/176).

**Comment by 404NetworkError** [comment]
Well, I guess just about any major change will break someone else's workflow. 🤷‍♀ It's all good.

**Comment by jabenninghoff** [comment]
@vitorgalvao, would you consider making, or accepting a PR, that generates a warning if `--appcast --token-conflicts` fails? Something like, "This request will not be automatically merged. We recommend waiting until the appcast is updated."

A warning might help prevent the issue in https://github.com/Homebrew/homebrew-cask/pull/76434, and would help my workflow.

**Comment by vitorgalvao** [comment]
> a PR, that generates a warning if (…) `--token-conflicts` fails

There’s no point in showing a warning for that case—it always needs to be reviewed.

> Something like, "This request will not be automatically merged.

No, that’s the wrong approach. You should never expect a request to be automatically merged.

> We recommend waiting until the appcast is updated."

Even worse. We definitely do not recommend that. Appcasts are as good as their synchronicity with the app updates. Some appcasts only need a bit of waiting, while others need to be replaced. If people stop submitting until appcasts are updated, we’ll never know which are bad.

The appcast check is to avoid unstable versions (betas and the like) being submitted when they shouldn’t. Those PRs take longer to be merged because it’s time consuming to check if the issue is with the appcast or the submission.

If on submission a user points out the appcast is outdated and links to proof, that can be done way faster. So what we need is more information in the PRs, not less PRs. I’m open to suggestion on how to make that clear.

**Comment by jabenninghoff** [comment]
Thanks for the explanation. What if `cask-repair` prompted the user to add that proof and included that in the PR it submitted?

**Comment by vitorgalvao** [comment]
> What if `cask-repair` prompted the user to add that proof and included that in the PR it submitted?

I question the usefulness of making the message show from `cask-repair`. I don’t think that’s the solution, as many people submit automatically without checking.

**Pull request closed without merging**
