### PR TITLE
fastmerge, prfixmaster: Add issue number to commit message header

### PR DESCRIPTION
**Pull request by jawshooah**
Emulate GitHub's behavior when squash-merging a PR.

---
This change is [Reviewable](https://reviewable.io/reviews/vitorgalvao/tiny-scripts/25)

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Oooh, great! I read the title of the issue this morning on my phone, so I didn’t even noticed who submitted it (no user images on notifications on mobile). I though “sounds reasonable, will implement this afternoon”. Now I came to see it and noticed it was actually a pull request. Thumbs up to that! Thank you.

**Comment by adidalal** [comment]
Is `message` a OS X utility I don't have, or just a syntax error?

[`message "Amending commit message with issue number (#${issue_number})"`](https://github.com/vitorgalvao/tiny-scripts/blob/8f70679cd613b514ac3a2cff2a6a76d09820be77/prfixmaster#L118)

When I try using after update:

```
 [.../homebrew-cask/Casks] > prfixmaster -c
/usr/local/bin/prfixmaster: line 118: message: command not found
[master ea70191] Added Synergy (1.7.6) (#22644)
[snip]
```

**Comment by jawshooah** [comment]
Ah, whoops, looks like that function is defined in `fastmerge` but not `prfixmaster`. Seems to be just a shim for `echo`, though.

**Comment by vitorgalvao** [comment]
Yep, that’s correct. At one point I decided to use `message` in some of the noisiest scripts (the ones that output more messages not specifically set by me) just in case I ever decided to change the styling of the output messages. `fastmerge` was made after `prfixmaster`, if I recall correctly.

**Pull request merged**
